import { AchievementContent } from '../components';

export const achievList: AchievementContent[] = [
  {
    title: 'Graduate',
    desc: 'Got my B.S. in Computer Science at the University of Brasilia. It was not easy, but I made it! My university degree is available under request. Send me an email.',
    earned: 'Earned in 2020',
    img: 'graduate',
    locked: false,
  },
  {
    title: 'Study Abroad',
    desc: 'Went to study in Santa Barbara for my Junior Year of High School. Leaving Brazil and going to another country was such an enlightening experience. I learned a lot about American culture and developed my English to a higher level.',
    earned: 'Earned in 2013',
    img: 'plane',
    locked: false,
  },
  {
    title: 'Doing Science',
    desc: 'Did an Undergraduate Research Project in agent communication in a machine learning environment. This was my first experience with the scientific process and the very first experience that made me want to work with artificial intelligence.',
    img: 'science',
    locked: false,
    earned: 'Earned in 2016',
  },
  {
    title: 'On My Own',
    desc: 'Did a Freelance. This experience was highly enriching. Being my boss, setting my times, and communicating with my clients properly, were some of the many experiences I developed during the project.',
    img: 'ios',
    locked: false,
    earned: 'Earned in 2017',
  },
  {
    title: 'Food Revolution',
    desc: 'Inspired by Ron Finley and his project, I started planting my garden and growing my food. In a while, I hope to have gathered enough experience to help transform food deserts into food forests and help spread his dream of edible gardens, one city at a time.',
    earned: 'Earned in 2020',
    img: 'plants',
    locked: false,
  },
  {
    title: 'Awesome Portfolio',
    desc: 'You are looking at it! Enjoy! This was my first project using React and one of my first websites. Personally not a big fan of web development, but doing this portfolio taught me a lot.',
    earned: 'Earned in 2020',
    img: 'website',
    locked: false,
  },
  {
    title: 'Guest Speaker',
    desc: "Speaker of Ethics and AI at Latin America Innovation Week, LATAM's most prominent event on innovation in the public sector.",
    earned: 'Earned in 2022',
    img: 'workshop',
    locked: false,
  },
  {
    title: 'Money Maker',
    desc: 'Closed a R$20.000 sponsorship deal for my robotics team with Autotrac, a company in the segment of technologies and logistics applied to automotive tracking.',
    earned: 'Earned in 2019',
    img: 'money',
    locked: false,
  },
  {
    title: 'Writer',
    desc: 'Publish a machine learning paper in one renowned computer science journal. The paper was published in 2022 in Neural Networks and Application. You can read the paper for free by clicking on its card on the publications page.',
    earned: 'Earned in 2021',
    img: 'paper',
    locked: false,
  },
  {
    title: 'Hacking the Market',
    desc: 'Successfully predicted the movement of three stocks in the Brazilian stock market using machine learning models. Those predictions were used to train a reinforcement learning model to allocate the desired resources, generating a return above 10% of the invested value. See the project to learn more.',
    earned: 'Earned in 2020',
    img: 'market',
    locked: false,
  },
  {
    title: 'Top of the Class',
    desc: 'Finished the Introduction to Artificial Intelligence course with the highest grade of my class.',
    earned: 'Earned in 2017',
    img: 'medal',
    locked: false,
  },
  {
    title: 'Early Start',
    desc: "Published an iOS App in high school before starting my bachelor's in Computer Science. I made two apps using XCode and Swift: My Zip Code and Quote's Book. You can't find these apps in the store anymore because the apple developer account is too expensive to maintain, but check out in the projects page.",
    earned: 'Earned in 2014',
    img: 'swift',
    locked: false,
  },
  {
    title: 'Get a Masters',
    desc: 'M.Sc. in Computer Science from Università degli Studi di Milano, graduated with honors (110/110 cum laude).',
    img: 'jedi',
    locked: false,
    earned: 'Earned in 2025',
  },
  {
    title: 'GAFAM',
    desc: 'Work for one of the giants GAFAM. Since I was a child, I glanced forward to being at the center of innovation and technology. In July 2023 I joined Amazon Italy as a Data Engineer Intern. Currently, I am a full-time Software Engineer for Amazon Logistics.',
    img: 'amazon',
    locked: false,
    earned: 'Joined Amazon in 2023',
  },
  {
    title: 'Get a Doctors',
    desc: 'I am doing my best to unlock this achievement, but to do so, I need first to be accepted at a university. I aim high. I am looking to enroll in one of the bests universities in the world. You can help me unlock this by accepting me at your university. Feel free to send me that acceptance letter.',
    img: 'doctor',
    locked: true,
    earned: 'Achievement Locked',
  },
  {
    title: 'Fancy Chef',
    desc: "Cook a fancy dinner for people I don't know. Just like working for a fancy restaurant for one night.",
    img: 'cook',
    locked: true,
    earned: 'Achievement Locked',
  },
  {
    title: 'Barista',
    desc: 'I want to become a certified barista and learn the art of making and appreciating coffee.',
    img: 'coffee',
    locked: true,
    earned: 'Achievement Locked',
  },
  {
    title: 'Kaggle Winner',
    desc: 'Win a medal in a Kaggle Competition.',
    img: 'kaggle',
    locked: true,
    earned: 'Achievement Locked',
  },
];
