interface SkillContent {
  title: string;
  years: number;
  projects: number;
  selfEval: number;
  group: number;
  desc?: string;
}

// Groups: 1 = Programming Languages, 2 = ML & Data, 3 = Web Development, 4 = Cloud & Infra
export const skills: SkillContent[] = [
  // Programming Languages (group 1)
  {
    title: 'Python',
    years: 8,
    projects: 5,
    selfEval: 10,
    group: 1,
    desc: 'Python is my main programming language.\nUsed extensively for data engineering,\nmachine learning, and backend development.',
  },
  {
    title: 'TypeScript',
    years: 3,
    projects: 4,
    selfEval: 10,
    group: 1,
    desc: 'Primary language for frontend development\nat Amazon. Used with React to build\nproduction planning interfaces.',
  },
  {
    title: 'Java',
    years: 3,
    projects: 2,
    selfEval: 6,
    group: 1,
    desc: 'Used for backend services\nand academic projects\nincluding software engineering courses.',
  },
  {
    title: 'SQL',
    years: 5,
    projects: 4,
    selfEval: 7,
    group: 1,
    desc: 'Query language for data pipelines\nand analytics. Used with PostgreSQL,\nAurora, and AWS Athena.',
  },
  // ML & Data (group 2)
  {
    title: 'TensorFlow',
    years: 4,
    projects: 4,
    selfEval: 8,
    group: 2,
    desc: 'Used for deep learning projects\nincluding customer segmentation\nwith autoencoders and\nreinforcement learning research.',
  },
  {
    title: 'Deep Learning',
    years: 5,
    projects: 4,
    selfEval: 9,
    group: 2,
    desc: 'DeepLearning.AI certified.\nApplied in research (5 publications)\nand industry (customer segmentation,\nautonomous agents).',
  },
  {
    title: 'RL',
    years: 4,
    projects: 3,
    selfEval: 9,
    group: 2,
    desc: 'Core research area.\nPublished AURORA trading system\nusing deep reinforcement learning\nin Neural Computing and Applications.',
  },
  {
    title: 'scikit-learn',
    years: 4,
    projects: 4,
    selfEval: 7,
    group: 2,
    desc: 'Used for NLP classification,\nclustering, and traditional ML\npipelines in industry and research.',
  },
  {
    title: 'HuggingFace',
    years: 2,
    projects: 2,
    selfEval: 6,
    group: 2,
    desc: 'Used for NLP classification models\nat Banco do Brasil for regulatory\ndocument analysis.',
  },
  {
    title: 'PySpark',
    years: 2,
    projects: 3,
    selfEval: 7,
    group: 2,
    desc: 'Used for building ETL data pipelines\nat Amazon, processing planning metrics\nacross EU and NA markets.',
  },
  {
    title: 'Research',
    years: 5,
    projects: 5,
    selfEval: 9,
    group: 2,
    desc: 'Five peer-reviewed publications\nacross IEEE, Springer, and MDPI.\nResearch in autonomous agents,\nreinforcement learning, and AI systems.',
  },
  // Web Development (group 3)
  {
    title: 'React',
    years: 3,
    projects: 4,
    selfEval: 12,
    group: 3,
    desc: 'Led frontend development at Amazon\nusing React and TypeScript.\nCreated 20+ shared components\nfor a multi-market planning platform.',
  },
  {
    title: 'Node.js',
    years: 3,
    projects: 4,
    selfEval: 7,
    group: 3,
    desc: 'Runtime for serverless backend\nservices on AWS Lambda.\nUsed across multiple microservices\nat Amazon.',
  },
  {
    title: 'FastAPI',
    years: 2,
    projects: 2,
    selfEval: 7,
    group: 3,
    desc: 'Python web framework for building\nREST APIs with automatic\nOpenAPI documentation.',
  },
  {
    title: 'Smithy',
    years: 2,
    projects: 2,
    selfEval: 6,
    group: 3,
    desc: 'Interface definition language\nfor API modeling and code generation.\nUsed at Amazon for service definitions.',
  },
  {
    title: 'Bootstrap',
    years: 3,
    projects: 3,
    selfEval: 7,
    group: 3,
    desc: 'CSS framework used for responsive\nlayouts and UI components\nacross multiple projects.',
  },
  {
    title: 'Storybook',
    years: 1,
    projects: 2,
    selfEval: 6,
    group: 3,
    desc: 'Component development and testing\nenvironment for building isolated\nUI components.',
  },
  {
    title: 'Cypress',
    years: 2,
    projects: 2,
    selfEval: 6,
    group: 3,
    desc: 'End-to-end testing framework\nused at Amazon for frontend\nquality assurance.',
  },
  // Cloud & Infra (group 4)
  {
    title: 'AWS',
    years: 3,
    projects: 5,
    selfEval: 14,
    group: 4,
    desc: 'Lambda, Step Functions, API Gateway,\nGlue, S3, DynamoDB, CDK, ECS,\nCloudFormation, EventBridge.\nAWS Certified Cloud Practitioner.',
  },
  {
    title: 'Relational DBs',
    years: 5,
    projects: 4,
    selfEval: 7,
    group: 4,
    desc: 'PostgreSQL, Aurora, MySQL.\nUsed for structured data storage\nacross multiple projects.',
  },
  {
    title: 'NoSQL DBs',
    years: 2,
    projects: 3,
    selfEval: 6,
    group: 4,
    desc: 'DynamoDB and S3-based data lakes.\nUsed at Amazon for high-throughput\nserverless architectures.',
  },
  {
    title: 'Docker',
    years: 3,
    projects: 3,
    selfEval: 7,
    group: 4,
    desc: 'Used for containerization\nand deployment. Experience with\nAWS ECS for container orchestration.',
  },
  {
    title: 'CI/CD',
    years: 3,
    projects: 4,
    selfEval: 7,
    group: 4,
    desc: 'Build and deployment pipelines,\nautomated testing, and infrastructure\nas code with CDK and CloudFormation.',
  },
  {
    title: 'Git',
    years: 6,
    projects: 4,
    selfEval: 7,
    group: 4,
    desc: 'Daily tool for version control.\n370 commits and 600+ code reviews\nat Amazon alone.',
  },
];
