interface SkillContent {
  title: string;
  linkedin: number;
  years: number;
  projects: number;
  selfEval: number;
  group: number;
  desc?: string;
}

export const skills: SkillContent[] = [
  {
    title: 'Python 3',
    linkedin: 7,
    years: 4,
    projects: 5,
    selfEval: 10,
    group: 1,
    desc: 'Python is my main programming language.\nMost of my programs were developed\nin Python and its libraries.\nI also give Python classes for newcomers.',
  },
  {
    title: 'Research',
    linkedin: 7,
    years: 4,
    projects: 5,
    selfEval: 10,
    group: 4,
    desc: 'Python is my main programming language.\nMost of my programs were developed\nin Python and its libraries.\nI also give Python classes for newcomers.',
  },
  {
    title: 'Swift',
    linkedin: 2,
    years: 6,
    projects: 1,
    selfEval: 8,
    group: 1,
    desc: 'Swift was my first language.\nI learned it through Treehouse in\nhighschool, and started my development\nskills with iOS Apps.',
  },
  {
    title: 'Numpy',
    linkedin: 2,
    years: 6,
    projects: 6,
    selfEval: 3,
    group: 2,
  },
  {
    title: 'C/C++',
    linkedin: 5,
    years: 5,
    projects: 5,
    selfEval: 9,
    group: 1,
    desc: 'C and C++ were my first,\nand most used, language in my\nbachelors degree. C is the main language\nthat helped me develop programming skills,\nit taught me to understand every aspect\nof core logic programming.',
  },
  {
    title: 'TypeScript',
    linkedin: 0,
    years: 1,
    projects: 3,
    selfEval: 4,
    group: 1,
    desc: 'Javascript and TypeScript is the language\nI use for web development.\nI am not a big fan, neither a big adept\nfor windows',
  },
  {
    title: 'RL',
    linkedin: 0,
    years: 2,
    projects: 2,
    selfEval: 10,
    group: 2,
  },
  {
    title: 'Deep Learning',
    linkedin: 0,
    years: 2,
    projects: 2,
    selfEval: 15,
    group: 2,
  },
  {
    title: 'Scikit Learn',
    linkedin: 0,
    years: 2,
    projects: 4,
    selfEval: 6,
    group: 2,
    desc: 'Sci-kit Learn was used\nin my starting projects on\nthe machine learning field.',
  },
  {
    title: 'Matplotlib',
    linkedin: 0,
    years: 3,
    projects: 6,
    selfEval: 7,
    group: 2,
    desc: 'Matplotlib is the main plot\nlibrary I used to create figures\nfor my data science reports.',
  },
  {
    title: 'TensorFlow',
    linkedin: 0,
    years: 4,
    projects: 4,
    selfEval: 15,
    group: 2,
  },
  {
    title: 'Bootstrap',
    linkedin: 0,
    years: 2,
    projects: 2,
    selfEval: 4,
    group: 3,
    desc: 'I used Bootstrap,\nBootstrap-Vue and Bootstrap-React\nin my web development.',
  },
  {
    title: 'React',
    linkedin: 0,
    years: 1,
    projects: 1,
    selfEval: 3,
    group: 3,
    desc: "This portfólio is made\nwith React and love!\nIsn't it awesome?!",
  },
  {
    title: 'MySQL',
    linkedin: 1,
    years: 1,
    projects: 4,
    selfEval: 6,
    group: 3,
    desc: 'I used MySQL once in a\nDatabase class, in which\nI learned not only the\nlanguage, but how to properly create a database.',
  },
  {
    title: 'Git/Github',
    linkedin: 5,
    years: 5,
    projects: 5,
    selfEval: 8,
    group: 4,
    desc: 'I learned Git and Github in my\nsecond semester at my university.\nI use it for all my projects.\nFeel free to follow me there.',
  },
  {
    title: 'Docker',
    linkedin: 0,
    years: 1,
    projects: 2,
    selfEval: 6,
    group: 4,
    desc: "I am not a heavy docker user,\nI haven't had many necessities to use it.\nBut I understand its core concepts and\nused in a Python library I developed.",
  },
  {
    title: 'XCode',
    linkedin: 2,
    years: 6,
    projects: 1,
    selfEval: 9,
    group: 3,
    desc: 'XCode is an iOS App development platform.\nI started using it before I enrolled in\nthe university and made several apps\nwith it.',
  },
  {
    title: 'LaTeX',
    linkedin: 3,
    years: 4,
    projects: 0,
    selfEval: 9,
    group: 4,
    desc: 'I dropped Word a long time ago.\nLatex is my main source for report\nand document creation.',
  },
];
